[default]
src = 'contracts'
test = 'test/foundry-test'
out = 'artifacts/contracts'
libs = ['lib', 'node_modules']
solc_version = '0.7.6'                                          
# auto_detect_solc = true                                       
optimizer = true                                             
optimizer_runs = 200                                         
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'contracts/=node_modules/@uniswap/lib/contracts/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    '@std=lib/forge-std/src/'
]
cache = true                                                  # whether to cache builds or not
fuzz_runs = 5000
etherscan_api_key = 'PSW8C433Q667DVEX5BCRMGNAH9FSGFZ7Q8'
libraries = [
    'contracts/libs/SqrtPriceMathPartial.sol:SqrtPriceMathPartial:0xafff7ba0904978c1c4bb49773e24dd8da57abcc6',
    'contracts/libs/TickMathExternal.sol:TickMathExternal:0x3df2b43b66d96409cad7f23bf5f699bae1aad144',
    '/Users/haythem96/Projects/DeFi/Options/Opyn/squeeth-monorepo/packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol:0x7a29594866CF3383555b8e051C80142e86d1058C'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config